// <auto-generated />
namespace SmartMvc.Data.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Create_MovimentItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_MovimentItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201806010127322_Create_MovimentItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
