// <auto-generated />
namespace SmartMvc.Data.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Invoice_Alteracao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Invoice_Alteracao));
        
        string IMigrationMetadata.Id
        {
            get { return "201805300138351_Invoice_Alteracao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
