//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMvc.Domain.Entities.Validations {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartMvc.Domain.Entities.Validations.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do Setor Requerido.
        /// </summary>
        public static string AreaNameIsRequired {
            get {
                return ResourceManager.GetString("AreaNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Caixa Requerida.
        /// </summary>
        public static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Impressão da Caixa Requerida.
        /// </summary>
        public static string BoxDatePrinter {
            get {
                return ResourceManager.GetString("BoxDatePrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do Setor Requerido.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Saída Requerida.
        /// </summary>
        public static string ExitTypeMovimentBoxIsRequired {
            get {
                return ResourceManager.GetString("ExitTypeMovimentBoxIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Emissão da Nota Fiscal Requerida.
        /// </summary>
        public static string InvoiceEmissionIsRequired {
            get {
                return ResourceManager.GetString("InvoiceEmissionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filial Requerida.
        /// </summary>
        public static string InvoiceFilialIsRequired {
            get {
                return ResourceManager.GetString("InvoiceFilialIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chave NF Requerida.
        /// </summary>
        public static string InvoiceKeyNfIsRequired {
            get {
                return ResourceManager.GetString("InvoiceKeyNfIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número Nota Fiscal Requerida.
        /// </summary>
        public static string InvoiceNumberIsRequired {
            get {
                return ResourceManager.GetString("InvoiceNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número de Série Requerida.
        /// </summary>
        public static string InvoiceNumberSerieIsRequired {
            get {
                return ResourceManager.GetString("InvoiceNumberSerieIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade Total Requerida.
        /// </summary>
        public static string InvoiceQuantityIsRequired {
            get {
                return ResourceManager.GetString("InvoiceQuantityIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Faturamento Requerida.
        /// </summary>
        public static string InvoiceTypeIsRequired {
            get {
                return ResourceManager.GetString("InvoiceTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade de Volumes Requerida.
        /// </summary>
        public static string InvoiceVolumeIsRequired {
            get {
                return ResourceManager.GetString("InvoiceVolumeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome da Área Requerida.
        /// </summary>
        public static string MovimentBoxArea {
            get {
                return ResourceManager.GetString("MovimentBoxArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Inicial de Movimentação Requerida.
        /// </summary>
        public static string MovimentBoxDateInitial {
            get {
                return ResourceManager.GetString("MovimentBoxDateInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nota Fiscal Requerida.
        /// </summary>
        public static string MovimentBoxInvoice {
            get {
                return ResourceManager.GetString("MovimentBoxInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Movimentação Requerida.
        /// </summary>
        public static string MovimentBoxTypeMoviment {
            get {
                return ResourceManager.GetString("MovimentBoxTypeMoviment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Caixa Requerida.
        /// </summary>
        public static string MovimentItemBox {
            get {
                return ResourceManager.GetString("MovimentItemBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Movimentação Requerida.
        /// </summary>
        public static string MovimentItemMovimentBox {
            get {
                return ResourceManager.GetString("MovimentItemMovimentBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ Requerido.
        /// </summary>
        public static string ProviderCnpjIsRequired {
            get {
                return ResourceManager.GetString("ProviderCnpjIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email de Contato Requerido.
        /// </summary>
        public static string ProviderEmailContactIsRequired {
            get {
                return ResourceManager.GetString("ProviderEmailContactIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome de Contato Requerido.
        /// </summary>
        public static string ProviderNameContactIsRequired {
            get {
                return ResourceManager.GetString("ProviderNameContactIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Razão Social Requerida.
        /// </summary>
        public static string ProviderNameIsRequired {
            get {
                return ResourceManager.GetString("ProviderNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UF Requerido.
        /// </summary>
        public static string ProviderUfIsRequired {
            get {
                return ResourceManager.GetString("ProviderUfIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login Requerido.
        /// </summary>
        public static string UserLoginIsRequired {
            get {
                return ResourceManager.GetString("UserLoginIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do Usuário Requerido.
        /// </summary>
        public static string UserNameIsRequired {
            get {
                return ResourceManager.GetString("UserNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password Requerido.
        /// </summary>
        public static string UserPasswordIsRequired {
            get {
                return ResourceManager.GetString("UserPasswordIsRequired", resourceCulture);
            }
        }
    }
}
